# Github Actions : workflow 자동화 도구 (<#> 참고 : https://zzsza.github.io/development/2020/06/06/github-action/)

name: ci

on:
  - push:
      branches: [ "main", "dev" ]
  - pull_request:
      branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

# Set JDK (<#> 참고 : https://github.com/cheese10yun/github-action)
      - name: Set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

# Gradle Caching (<#> 참고 : https://devjem.tistory.com/76)
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path:
            - ~/.gradle/wrapper
            - ~/.gradle/caches
            - key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            - restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

# AWS를 통한 배포 자동화를 위해 빌드된 프로젝트를 압축 (<#> 참고 : https://velog.io/@bagt/Github-Actions를-통한-배포)
      - name: Make zip file
        run: zip -r ./deploy.zip .
        shell: bash

